# Generated by Django 4.1.5 on 2023-01-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_article_images_alter_author_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isBigFormat',
            field=models.BooleanField(default=False),
        ),
    ]
