# Generated by Django 4.1.5 on 2023-02-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_article_isbigformat'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
